Добавляет имя наставника
htmlacademy-htmlcss/1703485-technomart-30 pull request #1
Opened 2021-01-19 17:45 UTC by agaphonova

2021-01-19 21:24 UTC, Vikkivi requested changes

2021-01-19 21:24 UTC, Vikkivi commented on Readme.md
> +* Наставник: `Виктория Постнова`.
Давай добавим ссылку на мою страницу по аналогии с тем, как это сделано для поля "Студент". На лайве было показано, как это можно сделать

2021-01-23 08:43 UTC, agaphonova commented on Readme.md
> +* Наставник: `Виктория Постнова`.
добавила

2021-01-24 07:33 UTC, Vikkivi commented on Readme.md
> +* Наставник: `Виктория Постнова`.
супер, принимаю)

2021-01-24 07:34 UTC, merged